apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kedacore
  namespace: flux-system
spec:
  interval: 1h
  url: https://kedacore.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  targetNamespace: keda
  chart:
    spec:
      chart: keda
      version: 2.13.0
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
  interval: 1h
  install:
    createNamespace: true
  values:
    replicaCount: 1
