apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-flux-fail
  namespace: flux-system
spec:
  releaseName: sample-flux-fail
  targetNamespace: sample-flux-fail
  interval: 1m0s
  chart:
    spec:
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      chart: charts/sample-flux-fail
  upgrade:
    remediation:
      retries: 2
  install:
    createNamespace: true
  rollback:
    timeout: 5m
    disableWait: true
    disableHooks: true
    recreate: true
    force: false
